<?xml version="1.0"?>
<package format="3">
  <name>drone_line_vision</name>
  <version>0.1.0</version>
  <description>Industrial camera pixel-domain black-line vision test node.</description>
  <maintainer email="gjl@example.com">gjl</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>drone_msgs</depend>
  <depend>ament_index_cpp</depend>
  <depend>libopencv-dev</depend>
  <exec_depend>hobot_usb_cam</exec_depend>
  <exec_depend>hobot_codec</exec_depend>
  <build_depend>hbm_img_msgs</build_depend>
  <exec_depend>hbm_img_msgs</exec_depend>
  <build_depend>yaml-cpp</build_depend>
  <exec_depend>yaml-cpp</exec_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
